Vagrant.configure("2") do |config|
    config.vm.box = "gyptazy/centos9-arm64"
    config.vm.box_version = "1.0.0"
    config.vm.provider "vmware_desktop" do |vmware|
        vmware.gui = true

    end
  end