Vagrant.configure("2") do |config|
    config.vm.box = "spox/ubuntu-arm"
    config.vm.box_version = "1.0.0"
    config.vm.provider "VAGRANTFILE_API_VERSION" do |config|
        config.gui = true
        config.ssh.insert_key = false
        config.vm.synced_folder ".", "/vagrant", disabled: true
        config.vm.provider :virtualbox do |v|
            v.memory = 256
            v.linked_clone = true
        end
        config.vm.define "app1" do |app|
            app.vm.hostname = "orc-app1.test"
            app.vm.network :private_network, ip: "192.168.60.4"
        end
        config.vm.define "app2" do |app|
            app.vm.hostname = "orc-app2.test"
            app.vm.network :private_network, ip: "192.168.60.5"
        end
        config.vm.define "db" do |db|
            app.vm.hostname = "orc-db.test"
            app.vm.network :private_network, ip: "192.168.60.6"
        end

    end
  end